apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: app
        image: rating:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
        ports:
        - containerPort: 8082